inputs_def:
  - handle: paths
    description: Input
    json_schema:
      type: array
      items:
        type: string
    value:
      []
  - handle: name
    json_schema:
      type: string
    value: output
  - handle: out_folder
    json_schema:
      type: string
      ui:widget: dir
    value: /oomol-storage/
outputs_def:
  - handle: file_address
    description: Output
    json_schema:
      type: string
icon: ":fa6-solid:file-pdf:currentColor:"
ui:
  default_width: 530
executor:
  name: python
  options:
    spawn: false
    entry: main.py
